config/routes.rb
Rails.application.routes.draw do

  root to: 'site/pages#index'  

  namespace :site do
    resources :projects
    get 'pages/index'
    get 'pages/profile'
  end

  get "/profile" => "site/pages#profile", as: :profile


  devise_scope :user do
    get "/login" => "devise/sessions#new" # custom path to login/sign_in
    get "/registration" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

   devise_for :users
  
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user == current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :title, :description, :price)
    end
end

app/controllers/site/pages_controller.rb
class Site::PagesController < ApplicationController
  
  def index
  end

  def profile
  	@projects = Project.all.where(user_id = current_user.id.to_s)
  end
  
end

app/controllers/site/projects_controller.rb
class Site::ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def page/home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site/pages_helper.rb
module Site::PagesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VlancerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title VlancerApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'header'
    = yield
    = render 'footer'

app/views/layouts/site/pages.html.haml
!!!
%html
  %head
    %title VlancerApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'header'
    = yield
    = render 'footer'

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th User
      %th Title
      %th Description
      %th Price
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.user
        %td= project.title
        %td= project.description
        %td= project.price
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b User:
  = @project.user
%p
  %b Title:
  = @project.title
%p
  %b Description:
  = @project.description
%p
  %b Price:
  = @project.price

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/site/pages/index.html.haml
%main.container{:role => "main"}
  %h1.mt-5 Биржа видео vlancer
  %p.lead
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %p

app/views/site/pages/profile.html.haml
%br
.container
  %h1.display-5= current_user.email
  / .row
  /   = render @projects

app/views/site/projects/_footer.html.haml
%footer.footer
  .container
    %span.text-muted  Биржа видео Vlancer 2018

app/views/site/projects/_header.html.haml
%header
  / Fixed navbar
  %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    .container
      %a.navbar-brand{:href => "#"} Видео биржа
      %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarCollapse.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            %a.nav-link{:href => "/"}
              Главная
          - if signed_in?
            %li.nav-item
              = link_to "Мой профиль", profile_path, class: 'nav-link'
          - else
            %li.nav-item
              %a.nav-link{:href => "#"} О сервисе
            %li.nav-item
              %a.nav-link{:href => "#"} Обратная связь

app/views/site/projects/_project.html.haml
.col-sm-3
  .card{}
    / %img.card-img-top{:alt => "Card image cap", :src => "http://placehold.it/50px50/"}/
    .card-body
      %h5.card-title=project.title
      %p.card-text=project.description
      / %a.btn.btn-primary{:href => "#"} Go

app/views/site/projects/index.html.haml
= render @projects